name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      
jobs:
  beautify:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          
      - name: Run beautysh
        uses: illvart/beautysh-action@latest
        with:
          args: 'setup-termux-alpine utils.sh --indent-size 4'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: illvart
          commit_user_email: illvartv@gmail.com
          commit_author: illvart <illvartv@gmail.com>
          commit_message: '[auto] ci: apply beautysh changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
